# .coderabbit.yaml
language: "ko-KR" # 한국말로 설정
early_access: true
enable_free_tire: true
auto_resolve_threads: false

reviews:
  profile: "chill" # 리뷰 너무 빡세게는 안한다는 뜻
  request_changes_workflow: false # 코드래빗이 리뷰 끝나면 알아서 PR 승인하게끔
  poem: false
  high_level_summary: true # 전체 요약 제공
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  web_search:
    enabled: true